---
- name: Garantir que o volume do Docker existe
  community.docker.docker_volume:
    name: "{{ n8n_volume_name }}"
    state: present

- name: Subir o container N8N
  community.docker.docker_container:
    name: "{{ n8n_container_name }}"
    image: "{{ n8n_image }}"
    state: started
    restart_policy: always
    ports:
      - "5678:5678"
    env:
      N8N_SECURE_COOKIE: "{{ n8n_secure_cookie }}"
    volumes:
      - "{{ n8n_volume_name }}:/home/node/.n8n"