---
  - name: Ajustar IP fixo
    ansible.builtin.copy:
      dest: /etc/netplan/00-installer-config.yaml
      content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp2s0:
                dhcp4: no
                dhcp6: no
                addresses: [10.1.1.68/24]
                routes:
                  - to: default
                    via: 10.1.1.1
                nameservers:
                  addresses: [10.1.1.1, 8.8.8.8] 