---
- name: Atualizar cache do apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar dependências do Docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present

- name: Adicionar chave GPG oficial do Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adicionar repositório Docker
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Atualizar cache do apt após adicionar repositório
  ansible.builtin.apt:
    update_cache: yes

- name: Instalar Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Garantir que o serviço Docker está ativo e iniciado
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Adicionar usuário ao grupo docker
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  notify: Reiniciar sessão
